config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'

  root :to => "static_pages#home"
  get "howto" => "static_pages#help"
  get "contact" => "contacts#new"
  get "cards" => "cards#new"

  get "cards/get_area"
  get "cards/update_courses", as: 'update_courses'
  get "cards/update_laboratories", as: 'update_laboratories'
  resources :cards
  resources :contacts

end

app/models/card.rb
class Card
  include ActiveModel::Model
  include ActiveModel::Associations
  
  belongs_to :department
  belongs_to :school

  attr_accessor :name, :kana_name, :department, :postalcode, :address_prefectural, :address_city, :address_street, :address_building, :tel, :email, :course, :laboratory, :free_text, :paper_template, :card_template

  validates :name,  presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  require "rexml/document"
  require "shellwords"
  require "securerandom"
  include REXML

  # GET /cards
  # GET /cards.json
  def index
    #@cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
    @prefectural = Prefectural.all
    @papers = PaperTemplate.all
    @cards = CardTemplate.all
    @course = [Course.new(name: "学部を選択してください", id:"")]
    @laboratory = [Laboratory.new(name: "学部を選択してください", id:"")]
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    mm = 3.543307
    forms = params.require(:card).permit(:name, :kana_name, :department, :postalcode, :address_prefectural, :address_city, :address_street, :address_building, :tel, :email, :course, :laboratory, :free_text, :card_template, :paper_template)

    paper_template = PaperTemplate.find(forms[:paper_template])
    paper = File.read("app/assets/images/paper/" + paper_template.path)

    card_template = CardTemplate.find(forms[:card_template])
    svg = REXML::Document.new(open("app/assets/images/card/" + card_template.path))

    # jikanganai
    svg.root.elements["//*[@id='text_name']"].text = forms[:name]

    if card_template.department
      if forms[:department].present?
        svg.root.elements["//*[@id='text_department']"].text =  School.find(Department.find(forms[:department]).school).name + Department.find(forms[:department]).name
      else 
        svg.root.elements["//*[@id='text_department']"].text = ""
      end
    end

    if card_template.course and forms[:course]
      if forms[:course].present?
        svg.root.elements["//*[@id='text_course']"].text = Course.find(forms[:course]).name
      else
        svg.root.elements["//*[@id='text_course']"].text =  ""
      end
    end

    
    if card_template.laboratory and forms[:laboratory]
      if forms[:laboratory].present?
        svg.root.elements["//*[@id='text_lab']"].text = Laboratory.find(forms[:laboratory]).name
      else
        svg.root.elements["//*[@id='text_lab']"].text =  ""
      end
    end

    if card_template.tel
      if forms[:tel].present?
        svg.root.elements["//*[@id='text_tel']"].text = forms[:tel]
      else
        svg.root.elements["//*[@id='text_tel']"].text = ""
      end
    end

    if card_template.email
      if forms[:email].present?
        svg.root.elements["//*[@id='text_email']"].text = forms[:email]
      else
        svg.root.elements["//*[@id='text_email']"].text = ""
      end
    end

    if card_template.free
      if forms[:free_text].present?
        svg.root.elements["//*[@id='text_free']"].text = forms[:free_text]
      else
        svg.root.elements["//*[@id='text_free']"].text = ""
      end
    end

    if card_template.address_city
      if forms[:address_city].present?
        svg.root.elements["//*[@id='text_address']"].text = Prefectural.find(forms[:address_prefectural]).name + forms[:address_city] + forms[:address_street] + forms[:address_building]
      else
        svg.root.elements["//*[@id='text_address']"].text = ""
      end
    end

    card_text = ""
    xMargin = paper_template.margin_x * mm
    yMargin = paper_template.margin_y * mm
    xSize = card_template.size_x * mm
    ySize = card_template.size_y * mm
    debug = ""
    for xNum in 0..(paper_template.cols - 1) do
      for yNum in 0..(paper_template.rows - 1) do
        x = xMargin + xSize * xNum
        y = yMargin + ySize * yNum
        svgText = svg.root.to_s
        
        svgText.gsub!(/<svg[^>]+>/, '')
        svgText.gsub!(/<\/svg>/, '')
        svgText.gsub!(/id='([^']+)'/) { "id='" + $1 + xNum.to_s + "_" + yNum.to_s + "'" }
        svgText.gsub!(/x='([0-9.]+)'/) { "x='" + ($1.to_f + x).to_s + "'" }
        svgText.gsub!(/y='([0-9.]+)'/) { "y='" + ($1.to_f + y).to_s + "'" }
        svgText.gsub!(/d='m ([0-9.]+),([0-9.]+)/) { "d='m #{($1.to_f + x).to_s},#{($2.to_f + y).to_s}" }

        paper.gsub!(/<g \/>/, svgText + "<g />")
      end
    end
    paper.gsub!(/"/, "'")

    filename = SecureRandom.hex
    svgFile = File.open("tmp/#{filename}.svg", 'w')
    svgFile.puts paper
    pdf = `cat tmp/#{filename}.svg | cairosvg -` 
    svgFile.close
    File.unlink("tmp/#{filename}.svg")

    #pdf = `echo "#{paper}" | cairosvg -`
    send_data pdf, filename: "card.pdf", type: "application/pdf", disposition: "inline"
    
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # from: http://qiita.com/inodev/items/9e08261c658c87cf777d
  def get_area
    records = Area.search_area(params[:search_code])
    render json: records
  end

  # cards/update_courses
  def update_courses
    @course = Course.where("department_id = ?", params[:department])
    respond_to do |format|
      format.js
    end
  end

  # cards/update_laboratories
  def update_laboratories
    @laboratory = Laboratory.where("department_id = ?", params[:department])
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params[:card]
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_course_select.html.erb
$("#card_course").html("<%= escape_javascript(options_for_select(@course.map{ |t| [t.name, t.id] })) %>");

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="my_contents">
  <h2>1. デザイン選択</h2>

  <%# Paper %>
  <div class="form-group has-success">
    <%= f.label :paper_template %><span class="asd">(必須)</span>
    <%= f.select :paper_template, @papers.collect{|t|[t.name,t.id]}, {prompt: t("guide.please_select")}, required: true, class: "form-control" %>
  </div>

  <%# Card %>
  <div class="form-group has-success">
    <%= f.label :card_template %><span class="asd">(必須)</span>
    <%= f.select :card_template, @cards.collect{|t|[t.name,t.id]}, {prompt: t("guide.please_select")}, required: true, class: "form-control" %>
  </div>



</div>
<div class="my_contents">
  <h2>2. 情報入力</h2>
  <%# Full Name %>
  <div class="form-group has-success">
    <%= f.label :name %><span class="asd">(必須)</span>
    <%= f.text_field :name, class: 'form-control', required: true, laceholder: t("guide.name_placeholder") %>
  </div>

  <%# Name Furigana %>
  <div class="form-group has-success">
    <%= f.label :kana_name %>
    <%= f.text_field :kana_name, class: 'form-control',  placeholder: '名前を入力してください' %>
  </div>

  <%# postacode %>
  <div class="form-group has-success">
    <%= f.label :postalcode, style: "display: block;" %></span>
    <%= f.text_field :postalcode, class: 'form-control', style: "display: inline; width: 25%" %>
    <%= f.button t("guide.postalcode_submit"), id: "getarea-button", type: "button", class: "btn btn-default" %>
    <span id="postalcode-result"></span>
  </div>

  <%# prefectural %>
  <% if false %>
  <div class="form-group has-success">
    <%= f.label :address_prefectural %>
    <%= f.select :address_prefectural, @prefectural.collect{|t|[t.name,t.id]}, {prompt: t("guide.please_select")}, class: "form-control selectpicker" %>
  </div>
  <% end %>

 <div class="form-group has-success">
    <%= f.label :address_prefectural %>
    <%= f.select :address_prefectural, @prefectural.collect{|t|[t.name,t.id]}, {prompt: t("guide.please_select")}, class: "form-control" %>
 </div>


 <%# city %>
 <div class="form-group has-success">
    <%= f.label :address_city %>
    <%= f.text_field :address_city, class: "form-control" %>
 </div>

 <%# street %>
 <div class="form-group has-success">
    <%= f.label :address_street %>
    <%= f.text_field :address_street, class: "form-control" %>
 </div>

 <%# building %>
 <div class="form-group has-success">
    <%= f.label :address_building %>
    <%= f.text_field :address_building, class: "form-control" %>
 </div>

 <%# telephone %>
 <div class="form-group has-success">
    <%= f.label :tel %>
    <%= f.text_field :tel, class: "form-control" %>
  </div>

  <%# email address %>
  <div class="form-group has-success">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <%# free text %>
  <div class="form-group has-success">
    <%= f.label :free_text %>
    <%= f.text_field :free_text, class: "form-control" %>
  </div>

  <%# department %>
  <div class="form-group has-success">
    <%= f.label :department %>
    <%= f.select :department, Department.all.collect{|t|[t.name, t.id]}, {prompt: t("guide.please_select")}, class: "form-control" %>
  </div>

  <%# course %>
  <div class="form-group has-success">
    <%= f.label :course %>
    <%= f.select :course, options_for_select(@course.collect{|course|[course.name, course.id]}, 0), {}, class: "form-control" %>
  </div>

  <%# laboratory %>
  <div class="form-group has-success">
    <%= f.label :laboratory %>
    <%= f.select :laboratory, options_for_select(@laboratory.collect{|laboratory|[laboratory.name, laboratory.id]}, 0), {}, class: "form-control" %>
  </div>
</div>


<div class="my_contents">
  <div class="actions">
    <%= f.submit "ダウンロード", class: "center-block btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>